Update index.html
htmlacademy-htmlcss/1888241-device-33 pull request #2
Opened 2022-01-27 10:09 UTC by qshatree

Разметил главную страницу.

2022-01-27 14:19 UTC, Kartaviy-arteom requested changes

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +          <img class="logo" src="" alt="Логотип-магазина-Девайс">
содержимое alt это строка, тебе не нужно собирать их через -. Ты можешь там написать просто alt="Логотип магазина Девайс">.

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +            <input name="search" placeholder="Текст поиска" type="search">
Тут тебе нужно использовать Label, у нас есть в критерии HTML-05, при необходимости его можно скрыть через visually hidden

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +        <h2>Порхает как бабочка,<br> жалит как пчела!</h2>
Это не заголовок данной секции, хоть он и нарисован крупно в макете. Заголовок это в основном про смысл всего раздела, не про дизайн. Можно еще прочитать такую маленькую статью https://doka.guide/html/h1-h6/ . Здесь можно использовать span

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +            <li class="nav-benefits-item-delivery">
Тут проблема с форматированием отступов, элементы на одном уровне имеют одинаковый отступ. Так ты сможешь бегло просмотрев понять, что куда вложено

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +
Этот блок https://disk.yandex.ru/i/EAouztLB2SxK3A можно вынести в отдельную секцию, что-то вроде преимуществ компании. Слева у тебя список кнопок, по нажатию на любую из них справа меняется контент. Т.е когда нажата доставка, справа инфо о доставке. Нажмем гарантия появится, текст о гарантии. Переключение можно реализовать без JS используя input type='radio'. Например так https://codepen.io/porsake/pen/abzKqjo

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +    <h2>О нас</h2>
нужно подправить отступы, заголовок внутри секции, class у секции в этом стиле наименования будет  about-us

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +    <p>Мы можем доставить ваш товар в самые отдалённые<br> уголки России транспортными компаниями:</p>
тебе тут не нужны br, текст перенесется как в макете когда ты добавишь стили.

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +    </address>
здесь href="tel:88128121212" лучше указать номер через +7. href="tel:+78128121212"

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +
Это может быть как и section, но наверное лучше даже сформировать при помощи div, как обертки. Еще label нужен. br в параграфе тут не нужны, перед form лишний отступ

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +  <h2 class="visually-hidden">Девайс</h2>
здесь заголовок не обязателен и данный не информативен

2022-01-27 14:19 UTC, Kartaviy-arteom commented on index.html
> +          <a href="htmlacademy.ru">.html<br>academy</a>
для логотипов лучше использовать картинки, даже если это текст. У нас в макете этот логотип векторное изображение. Его можно реализовать по разному. Например вставив в ссылку svg. https://htmlacademy.ru/blog/boost/frontend/short-4 .

2022-02-05 09:16 UTC, Kartaviy-arteom requested changes

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +        </form>
Вот эту часть лучше вынести из nav, она здесь не уместна.
Добавляя label класс visually-hidden, будут скрыты его потомки, в том числе input. Т.е необходимо либо оставить этот класс только у span c текстом поиск по сайту, а у label убрать. Или вынести input из label, а класс visually-hidden оставить в этом месте только у label. Перед button лишний отступ.

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +      </ul>
Вот это часть наверное лишняя, она заменяется кодом ниже

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +            <img class="quadrocopter-img" src="#" alt="Картинка с квадрокоптером">
не совсем удачный Alt, слово картинка лишнее.

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +            <div>Этот обычный, на первый взгляд, квадрокоптер оснащен мощным лазером, замаскированным под стандартную камеру.</div>
тут можно использовать тег P

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +          <div class="swiper-slide quadrocopter active">
можно оставить класс просто slide, swiper - это название популярной библиотеки, это было в примере, но тут это не нужно

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +
вот эту часть можно объединить в секцию

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +      <section class="benefits-radio">
рекомендуется что бы у секции был свой заголовок, например это у нас: условия работы или преимущества компании. Он будет уровня h2, внутри аккордеона тогда получатся уровня h3 Наверное класс тут будет уместен просто benefits

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +            <input type="radio" name="benefits-radio-accordion" checked="checked" id="radio-delivery">
у всех трех инпутов указан атрибут checked="checked", это значит предварительно выбранный. У связанных радиокнопок, может быть выбрана только одна из них. Нужно оставить только первому input

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +            <div class="accordion-header">ДОСТАВКА</div>
внутри label тебе не обязательно использовать какой-то тег

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +              </div>
у тебя есть див с классом accordion-content, а затем еще один div. Скорее всего второй будет лишним

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +        <a class="more-about-us" href="#">ПОДРОБНЕЕ О НАС</a>
тебе не нужно давать класс ссылке, основываясь на тексте внутри, если он изменится это начнет тебя запутывать. Это момент нам лучше будет проговорить. Так же у тебя есть ряд одинаковых ссылок в макете, которые выглядят одинаково, если ты им дашь одинаковый класс, ты можешь написать для них стили один раз и они все станут как в макете.

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +      </section>
выглядит так, как будто p и h3, вложены в h2, но это не так. использование h3 здесь спорно

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +      </div>
это нам лучше обсудить как сделать лучше

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +        <a href="htmlacademy.ru">.html<br>academy</a>
это лого будет картинкой

2022-02-05 09:16 UTC, Kartaviy-arteom commented on index.html
> +          <img src="facebook.svg"  alt="facebook-logo">
если ты сделаешь так то у тебя будет ссылка, а рядом просто картинка.

2022-02-18 03:11 UTC, qshatree commented
Пересоздал

2022-02-18 03:11 UTC, closed without merging